# 3-Var: patch_size [8, 8] + embed_dim 256 + enc_depth 6
name: parseq-p8x8-embed256-enc-depth6
_target_: strhub.models.parseq.system.PARSeq

# Data
patch_size: [8, 8]

# Architecture
embed_dim: 256
enc_num_heads: 8
enc_mlp_ratio: 4
enc_depth: 6
dec_num_heads: 8
dec_mlp_ratio: 4
dec_depth: 1

# Training
lr: 0.0007
weight_decay: 0.0001
perm_num: 4
perm_forward: true
perm_mirrored: true
dropout: 0.1

# Decoding mode (test)
decode_ar: false
refine_iters: 1
