name: parseq-cnn-repvit-hybrid-dec-depth2
_target_: strhub.models.parseq_hybrid.system.PARSeq

# Data & Geometry
patch_size: [ 4, 8 ]

# CNN Backbone (RepViT) + 4 ViT + 2 Camadas de Decoder
backbone: repvit_m0_9
pretrained_backbone: false
dw_stride: [ 1, 2 ]
pos_embed_type: learned

# Architecture
embed_dim: 384
enc_num_heads: 6
enc_mlp_ratio: 4
enc_depth: 4          # 4 camadas encoder
dec_num_heads: 12
dec_mlp_ratio: 4
dec_depth: 2          # 2 camadas decoder

# Training
lr: 5e-4
weight_decay: 1e-4
perm_num: 4
perm_forward: true
perm_mirrored: true
perm_forward_weight: 2.0
label_smoothing: 0.05
dropout: 0.1

# Decoding mode (inference)
decode_ar: false
refine_iters: 1
