# 2-Var: embed_dim 192 + enc_mlp_ratio 2
name: parseq-embed192-enc-mlp2
_target_: strhub.models.parseq.system.PARSeq

# Data
patch_size: [4, 8]

# Architecture
embed_dim: 192
enc_num_heads: 6
enc_mlp_ratio: 2
enc_depth: 12
dec_num_heads: 12
dec_mlp_ratio: 4
dec_depth: 1

# Training
lr: 0.0009
weight_decay: 0.0001
perm_num: 4
perm_forward: true
perm_mirrored: true
dropout: 0.1

# Decoding mode (test)
decode_ar: false
refine_iters: 1
