# Multi-Var: Base compacta com patch [8, 8]
name: parseq-p8x8-base-compact
_target_: strhub.models.parseq.system.PARSeq

# Data
patch_size: [8, 8]

# Architecture
embed_dim: 384
enc_num_heads: 6
enc_mlp_ratio: 3
enc_depth: 8
dec_num_heads: 12
dec_mlp_ratio: 3
dec_depth: 1

# Training
lr: 0.00045
weight_decay: 0.001
perm_num: 4
perm_forward: true
perm_mirrored: true
dropout: 0.15

# Decoding mode (test)
decode_ar: false
refine_iters: 1
