name: parseq-cnn-repvit-heads6-6
_target_: strhub.models.parseq_hybrid.system.PARSeq

# Data & Geometry
patch_size: [ 4, 8 ]

# CNN Backbone (RepViT) + 4 ViT com 6 cabeças no encoder e 6 no decoder
backbone: repvit_m0_9
pretrained_backbone: false
dw_stride: [ 1, 2 ]
pos_embed_type: learned

# Architecture
embed_dim: 384
enc_num_heads: 6
enc_mlp_ratio: 4
enc_depth: 4
dec_num_heads: 6      # 6 cabeças no decoder
dec_mlp_ratio: 4
dec_depth: 1

# Training
lr: 5e-4
weight_decay: 1e-4
perm_num: 4
perm_forward: true
perm_mirrored: true
perm_forward_weight: 2.0
label_smoothing: 0.05
dropout: 0.1

# Decoding mode (inference)
decode_ar: false
refine_iters: 1
