# Multi-Var: Tiny adaptado para patch [8, 8]
name: parseq-alpr-tiny-p8x8
_target_: strhub.models.parseq.system.PARSeq

# Data
patch_size: [8, 8]

# Architecture
embed_dim: 192
enc_num_heads: 3
enc_mlp_ratio: 3
enc_depth: 6
dec_num_heads: 6
dec_mlp_ratio: 3
dec_depth: 1

# Training
lr: 0.0009
weight_decay: 0.0001
perm_num: 4
perm_forward: true
perm_mirrored: true
dropout: 0.1

# Decoding mode (test)
decode_ar: false
refine_iters: 1
